apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-api
  template:
    metadata:
      labels:
        app: app-api
    spec:
      containers:
      - name: app-api
        image: addhome2001/cluster-app-api:0.1.0
        ports:
        - name: app-api-port
          containerPort: 8000

---

kind: Service
apiVersion: v1
metadata:
  name: app-api-service
spec:
  type: NodePort
  selector:
    app: app-api
  ports:
  - port: 8000
    protocol: TCP
    targetPort: app-api-port